// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feeds.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createFeed = `-- name: CreateFeed :one
INSERT INTO  feeds(id,createdAt,updatedAt,content,createdBy) 
VALUES ( $1,$2,$3,$4,$5 )
RETURNING id, createdat, updatedat, content, createdby
`

type CreateFeedParams struct {
	ID        uuid.UUID
	Createdat time.Time
	Updatedat time.Time
	Content   sql.NullString
	Createdby uuid.UUID
}

func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, createFeed,
		arg.ID,
		arg.Createdat,
		arg.Updatedat,
		arg.Content,
		arg.Createdby,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Createdat,
		&i.Updatedat,
		&i.Content,
		&i.Createdby,
	)
	return i, err
}

const getUserPosts = `-- name: GetUserPosts :one
SELECT id, createdat, updatedat, content, createdby FROM feeds where createdBy=$1
`

func (q *Queries) GetUserPosts(ctx context.Context, createdby uuid.UUID) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getUserPosts, createdby)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Createdat,
		&i.Updatedat,
		&i.Content,
		&i.Createdby,
	)
	return i, err
}
