// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Feed struct {
	ID        uuid.UUID
	Createdat time.Time
	Updatedat time.Time
	Content   sql.NullString
	Createdby uuid.UUID
}

type FeedFollow struct {
	ID        uuid.UUID
	Createdat time.Time
	Updatedat time.Time
	UserID    uuid.UUID
	FeedID    uuid.UUID
}

type User struct {
	ID        uuid.UUID
	Createdat time.Time
	Updatedat time.Time
	Name      string
	ApiKey    string
}
